import "dart:html";import "dart:convert";import "dart:async";WebSocket j;void main(){o();querySelector("#submit").onClick.listen((MouseEvent k){print("Send mesaage");var h=querySelector("#editor div div div .editor");h.querySelectorAll("br").forEach((Element k){k.text="<{#}>";});var n=JSON.encode({'Type':'new','Data':{'channel':'piazza','content':h.text}});print(h.text);j.send(n);h.text="";querySelector("button.close").click();});var m=querySelectorAll(".colors .color-box");const l=" fa fa-check";for(Element g in m){g.onClick.listen((MouseEvent k){var BB=g.id;var i=g.getAttribute("class");if(i.indexOf(l)!=0){g.setAttribute("class",i+l);for(Element g in m){if(g.id!=BB){i=g.getAttribute("class").replaceAll(l,"");g.setAttribute("class",i);}}}});}}void o([int h=2]){var k=false;print("Connecting to websocket");j=new WebSocket('ws://127.0.0.1:4000/ws');void l(){if(!k){new Timer(new Duration(milliseconds:1000*h),()=>o(h*2));}k=true;}j.onOpen.listen((i){print('Connected');h=2;});j.onClose.listen((i){print('Websocket closed, retrying in ${h} seconds');l();});j.onError.listen((i){print("Error connecting to ws");l();});j.onMessage.listen((MessageEvent i){var g=JSON.decode(i.data.toString());switch (g["Type"]){case "newMsg":var n=new Element.html('''
          <div id="${g["Data"]["ID"]}" class="col-xs-12 col-sm-6 col-md-4">
		      	<div class="content">
			      	<div class="panel-body">${g["Data"]["Content"]}</div>
              <div class="panel-footer" style="background-color: ${g["Data"]["Color"]};">
                <i class="fa fa-clock-o"></i>
				        <a>time</a>
              </div>
            </div>
          </div>
        ''');var m=querySelector("body .container .row div");m.parent.insertBefore(n,m);break;case "error":print(g["Data"]);break;}});}const CB='mangledGlobalNames';class q{static const String DB="Chrome";static const String EB="Firefox";static const String FB="Internet Explorer";static const String GB="Opera";static const String HB="Safari";final String AB;final String minimumVersion;const q(this.AB,[this.minimumVersion]);}class s{const s();}class t{final String name;const t(this.name);}class u{const u();}class v{const v();}