import "dart:html";import "dart:convert";import "dart:async";WebSocket k;void main(){q();querySelector("#submit").onClick.listen((MouseEvent j){print("Send mesaage");var h=querySelector("#editor div div div .editor");h.querySelectorAll("br").forEach((Element j){j.text="<{#}>";});var n=querySelector(".colors .fa.fa-check").id;var o=JSON.encode({'Type':'new','Data':{'channel':'piazza','content':h.text,'color':n}});print(h.text);k.send(o);h.text="";querySelector("button.close").click();});var m=querySelectorAll(".colors .color-box");const l=" fa fa-check";for(Element g in m){g.onClick.listen((MouseEvent j){var CB=g.id;var i=g.getAttribute("class");if(i.indexOf(l)==-1){g.setAttribute("class",i+l);for(Element g in m){if(g.id!=CB){i=g.getAttribute("class").replaceAll(l,"");g.setAttribute("class",i);}}}});}}void q([int i=2]){var l=false;print("Connecting to websocket");k=new WebSocket('ws://127.0.0.1:4000/ws');void m(){if(!l){new Timer(new Duration(milliseconds:1000*i),()=>q(i*2));}l=true;}k.onOpen.listen((j){print('Connected');i=2;});k.onClose.listen((j){print('Websocket closed, retrying in ${i} seconds');m();});k.onError.listen((j){print("Error connecting to ws");m();});k.onMessage.listen((MessageEvent j){var h=JSON.decode(j.data.toString());switch (h["Type"]){case "newMsg":var g;switch (h["Data"]["Color"]){case 0:g="default";break;case 1:g="red";break;case 2:g="pink";break;case 3:g="orange";break;case 4:g="yellow";break;case 5:g="lime";break;case 6:g="green";break;case 7:g="teal";break;case 8:g="blue";break;case 9:g="indigo";break;case 10:g="deep-purple";break;case 11:g="purple";break;}var o=new Element.html('''
          <div id="${h["Data"]["ID"]}" class="col-xs-12 col-sm-6 col-md-4">
		      	<div class="content">
			      	<div class="panel-body">${h["Data"]["Content"]}</div>
              <div class="panel-footer ${g}"">
                <i class="fa fa-clock-o"></i>
				        <a>time</a>
              </div>
            </div>
          </div>
        ''');var n=querySelector("body .container .row div");n.parent.insertBefore(o,n);break;case "error":print(h["Data"]);break;}});}const DB='mangledGlobalNames';class s{static const String EB="Chrome";static const String FB="Firefox";static const String GB="Internet Explorer";static const String HB="Opera";static const String IB="Safari";final String BB;final String minimumVersion;const s(this.BB,[this.minimumVersion]);}class t{const t();}class u{final String name;const u(this.name);}class v{const v();}class AB{const AB();}