import "dart:html";import "dart:convert";import "dart:async";WebSocket k;void main(){q();querySelector("#submit").onClick.listen((MouseEvent j){print("Send mesaage");var h=querySelector("#editor div div div .editor");h.querySelectorAll("br").forEach((Element j){j.text="<{#}>";});var n=querySelector(".colors .fa.fa-check").id;var o=JSON.encode({'Type':'new','Data':{'channel':'piazza','content':h.text,'color':n}});print(h.text);k.send(o);h.text="";querySelector("button.close").click();});querySelectorAll(".content .panel-footer").forEach((Element DB){s(DB);});var m=querySelectorAll(".colors .color-box");const l=" fa fa-check";for(Element g in m){g.onClick.listen((MouseEvent j){var EB=g.id;var i=g.getAttribute("class");if(i.indexOf(l)==-1){g.setAttribute("class",i+l);for(Element g in m){if(g.id!=EB){i=g.getAttribute("class").replaceAll(l,"");g.setAttribute("class",i);}}}});}}void q([int i=2]){var n=false;print("Connecting to websocket");k=new WebSocket('ws://127.0.0.1:4000/ws');void o(){if(!n){new Timer(new Duration(milliseconds:1000*i),()=>q(i*2));}n=true;}k.onOpen.listen((j){print('Connected');i=2;});k.onClose.listen((j){print('Websocket closed, retrying in ${i} seconds');o();});k.onError.listen((j){print("Error connecting to ws");o();});k.onMessage.listen((MessageEvent j){var h=JSON.decode(j.data.toString());switch (h["Type"]){case "newMsg":var g;switch (h["Data"]["Color"]){case 0:g="default";break;case 1:g="red";break;case 2:g="pink";break;case 3:g="orange";break;case 4:g="yellow";break;case 5:g="lime";break;case 6:g="green";break;case 7:g="teal";break;case 8:g="blue";break;case 9:g="indigo";break;case 10:g="deep-purple";break;case 11:g="purple";break;}var l=new Element.html('''
          <div id="${h["Data"]["ID"]}" class="col-xs-12 col-sm-6 col-md-4">
		      	<div class="content">
			      	<div class="panel-body">${h["Data"]["Content"]}</div>
              <div class="panel-footer ${g}">
                <i class="fa fa-clock-o"></i>
				        <a>time</a>
              </div>
            </div>
          </div>
        ''');s(l.querySelector(".panel-footer"));var m=querySelector("body .container .row div");if(m==null){querySelector("body .container .row").append(l);}else{m.parent.insertBefore(l,m);}break;case "error":print(h["Data"]);break;}});}void s(Element g){g.onMouseEnter.listen((MouseEvent i){var h=new Element.html('<div><i class="fa fa-times"></i></div>');h.onClick.listen((MouseEvent i){var j=h.parent.parent.parent;j.remove();k.send(JSON.encode({'Type':'remove','Data':{'id':j.id}}));});g.append(h);});g.onMouseLeave.listen((MouseEvent i){g.querySelector("div").remove();});}const FB='mangledGlobalNames';class t{static const String GB="Chrome";static const String HB="Firefox";static const String IB="Internet Explorer";static const String JB="Opera";static const String KB="Safari";final String CB;final String minimumVersion;const t(this.CB,[this.minimumVersion]);}class u{const u();}class v{final String name;const v(this.name);}class AB{const AB();}class BB{const BB();}